### PR TITLE
Add Deltares global flood map documentation

### PR DESCRIPTION
**Pull request by mmcfarland**
Storage documentation and example blob-access notebook for Deltares global flood map dataset.

Notes:  missing source documentation link. @brunosan do we have a link to any Deltares documentation or detail (I've got an old email that contains a draft document)

/cc @agentmorris tagged for a review for consistency and copy
/cc @TomAugspurger tagged because you often point out better ways to use xarray

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Looks great. A few questions:

1. In the "Myanmar inundation, SLR 2050/250y RP" plot, are there values *below* zero? If not, maybe set `vmin=0` in the `floded.inun.plot` to cut the colorbar off there.
2. The opening sentence feels a bit stiff.
3. There are a few acronyms that are unexplained (like SLR, DEM, GIS)
4. Have we told Deltares about the incorrect(?) time values in the NetCDF files? In case it helps, I pulled the 2018slr_rp0100 file and `ncdump` shows a value of `18263`. IIUC, 18,263 days from 1960-01-01 is 2010-01-01 
```
ncdump -v time GFM_global_NASADEM90m_2018slr_rp0100_masked.nc 
netcdf GFM_global_NASADEM90m_2018slr_rp0100_masked {
dimensions:
        time = UNLIMITED ; // (1 currently)
        lat = 216000 ;
        lon = 432000 ;
variables:
        double time(time) ;
                time:units = "Days since 1960-01-01 00:00:00" ;
                time:calendar = "gregorian" ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
        double lat(lat) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
        double lon(lon) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
        char projection ;
                projection:long_name = "wgs84" ;
                projection:EPSG_code = "EPSG:4326" ;
                projection:proj4_params = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" ;
                projection:grid_mapping_name = "latitude_longitude" ;
        float inun(time, lat, lon) ;
                inun:_FillValue = -9999.f ;
                inun:coordinates = "lat lon" ;
                inun:units = "m" ;
                inun:standard_name = "water_surface_height_above_reference_datum" ;
                inun:long_name = "Coastal flooding" ;
                inun:comment = "water_surface_reference_datum_altitude is given in file /mnt/globalRuns/CopyOfData/NASADEM_90m.tif" ;

// global attributes:
                :source = "Global Tide and Surge Model v3.0 - ERA5" ;
                :institution = "Deltares" ;
                :title = "GFM - NASA DEM 90m - 2018 slr - 0100-year return level" ;
                :references = "https://www.deltares.nl/en/" ;
                :Conventions = "CF-1.6" ;
                :project = "Microsoft Planetary Computer - Global Flood Maps" ;
                :config_file = "/mnt/globalRuns/watermask_post_NASA/run_rp0100_slr2018/coastal_inun.ini" ;
data:

 time = 18263 ;
}```
5. I haven't 100% confirmed, but I think
```python
present = mds["inun"].sel(time="2018-01-01")
future = mds["inun"].sel(time="2050-01-01")

diff = future - present
diff = diff.where(diff > 0)
```

is equivalent to `mds["inun"].diff("time").where(lambda x: x > 0)`. Or

```python
diff = mds["inun"].diff("time")
diff = diff.where(diff > 0)
```

if you want to avoid the lambda.

**Review by TomAugspurger — APPROVED** [review]

**Comment by mmcfarland** [comment]
Thanks for the comments, I'll do a pass at incorporating them in 👍. For 4, I have flagged it to them in an email previously, but it didn't get resolved. The draft documentation they provided on the variables also indicates:

> single time output value, not used (default value of 01-Jan-2010)

**Comment by brunosan** [comment]
This is the first dataset where the  "Source" is us. Meaning we host the canonical data. 
I've set the  `Source` link to Deltares homepage. We could put something like "We are the canonical set, procured under contract by Deltares" but it feels to weird.

**Comment by mmcfarland** [comment]
@agentmorris I refactored the storage data paths and updated the docs/notebook to match. This is ready for a review.

**Pull request merged**
